name: Labeling new issue
on:
    issues:
        types: ['opened']
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: Renato66/auto-label@v2
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  ignore-comments: true
                  labels-synonyms: '{"LGMSOC21":["LGMSOC21", "LGMSOC", "lgmsoc", "LGM-SOC","LGM-SOC21","lgm-soc","LGM-SOC21","lgm-soc21","LGM-soc", "lgm-SOC", "Lgm-soc"]}'
